triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/InformationController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/MemberController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/domain/Community.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/domain/Makemate.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/domain/Member.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/domain/Travelinfo.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/domain/Travelreview.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/domain/city.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/domain/country.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/domain/land.java
triptalkie/src/main/resources/templates/pages/information/list.html

**개요**
domain class 파일 작성
**구현 내용**
domain class 파일 member, makemate, community, travelinfo, travelreview, land, country, city 작성
**테스트 방법**
-

feat : domain class 파일 작성

---

triptalkie/pom.xml
triptalkie/src/main/java/com/walkietalkie/triptalkie/config/ConfigTemp.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/config/CryptoConfig.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/TestNamjooController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/domain/Member.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/mapper/MemberMapper.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/MemberService.java
triptalkie/src/main/resources/static/css/footer.css
triptalkie/src/main/resources/static/css/styleguide.css
triptalkie/src/main/resources/templates/fragments/header.html
triptalkie/src/main/resources/templates/pages/member/signup.html

**개요**
- styleguid style 일부 수정
- footer 폰트 크기 변경
- header에 회원가입 링크 입력
**구현 내용**
- styleguid style 일부 수정
- footer 폰트 크기 변경
- header에 회원가입 링크 입력
**테스트 방법**
-

Feat/yeh UI setting

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/HomeController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/TestYehController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/mapper/MemberMapper.java
triptalkie/src/main/resources/static/js/member.js
triptalkie/src/main/resources/templates/fragments/header.html
triptalkie/src/main/resources/templates/layouts/base.html
triptalkie/src/main/resources/templates/pages/member-2/signup.html
triptalkie/src/test/java/com/walkietalkie/triptalkie/test/member/YehMemberMapperTest.java
triptalkie/src/test/java/com/walkietalkie/triptalkie/test/member/YehMemberServiceTest.java
triptalkie/src/test/java/com/walkietalkie/triptalkie/test/member/YehMemberServiceTransactionTest.java

**개요**
테스트를 위한 memberController, memberMapper, memberServiceTest 파일 생성
**구현 내용**
- memberController 생성
- memberMapper 생성
- memberServiceTest 생성
**테스트 방법**

feat: 테스트를 위한 memberController, memberMapper, memberServiceTest 파일 생성

---

triptalkie/src/main/resources/static/css/member.css
triptalkie/src/main/resources/static/css/styleguide.css
triptalkie/src/main/resources/templates/pages/member-2/login.html

**개요**
로그인 클릭 시 나오는 모달창 ui 생성
**구현 내용**
- 로그인 클릭 시 db와 확인 후 아이디 혹은 비밀번호 틀렸을 경우 뜨는 모달창을 구현하였다.
**테스트 방법**
- js 추가하여 아이디와 비밀번호를 저장된 값과 다르게 입력하여 뜨는지 확인한다.

feat: 로그인 클릭 시 나오는 모달창 ui 생성

---

triptalkie/src/main/resources/static/css/customerservice.css
triptalkie/src/main/resources/static/js/customerservice.js
triptalkie/src/main/resources/templates/pages/customerservice/FAQ.html
triptalkie/src/main/resources/templates/pages/customerservice/QnA.html

**개요**
customerservice  ui 구현
**구현 내용**
customerservice  의 공지사항, FAQ, QnA 페이지 틀 제작
**테스트 방법**
Controller와 페이지 연결해 화면 확인

feat:customerservice  ui 구현

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/mapper/MypageMapper.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/MypageService.java
triptalkie/src/main/resources/com/walkietalkie/triptalkie/mapper/MypageMapper.xml
triptalkie/src/main/resources/templates/pages/member/mypage.html

**개요**
feat:mypage ui 완료
**구현 내용**
feat:mypage ui 구현 완료
**테스트 방법**
Controller와 페이지 연결해 화면 확인

feat:mypage ui 완료

---

triptalkie/src/main/resources/static/css/styleguide.css
triptalkie/src/main/resources/static/css/travel-review.css
triptalkie/src/main/resources/static/js/travel-review.js
triptalkie/src/main/resources/templates/pages/travel-review/detail-review.html
triptalkie/src/main/resources/templates/pages/travel-review/findTravelreviewAllList.html

**개요**
여행 후기 페이지 전체 ui 일부 수정
**구현 내용**
- 리스트, 상세페이지 전체 ui 수정
- 버튼 디자인 수정
**테스트 방법**
- 프로젝트 실행으로 확인 할 수 있다

fix: 여행 후기 페이지 전체 ui 일부 수정

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/CustomerserviceController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/MypageController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/TestNamjooController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/mapper/MypageMapper.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/MypageService.java
triptalkie/src/main/resources/com/walkietalkie/triptalkie/mapper/MypageMapper.xml
triptalkie/src/main/resources/static/js/mypage.js
triptalkie/src/main/resources/templates/fragments/header.html
triptalkie/src/main/resources/templates/fragments/mypage-list.html
triptalkie/src/main/resources/templates/layouts/base.html
triptalkie/src/main/resources/templates/pages/customerservice/notice.html
triptalkie/src/main/resources/templates/pages/member/login.html
triptalkie/src/main/resources/templates/pages/mypage/myinformation.html
triptalkie/src/main/resources/templates/pages/mypage/password-check.html
triptalkie/src/main/resources/templates/pages/mypage/update-myinfo.html
triptalkie/src/test/java/com/walkietalkie/triptalkie/test/member/NamMemberServiceTest.java

**개요**
마이페이지-내정보수정-비밀번호 체크 구현 완료
**구현 내용**
마이페이지-내정보수정버튼-비밀번호 체크->비밀번호 틀리면 모달창으로 알림/비밀번호 맞으면 내정보수정 페이지로
**테스트 방법**
JUnit으로 회원정보 update 확인,
화면에서 출력확인

feat:내정보수정-비밀번호 체크 구현 완료

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/CityController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/TravelReviewController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/mapper/CityMapper.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/mapper/CountryMapper.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/CityService.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/CountryService.java
triptalkie/src/main/resources/com/walkietalkie/triptalkie/mapper/CityMapper.xml
triptalkie/src/main/resources/com/walkietalkie/triptalkie/mapper/CountryMapper.xml
triptalkie/src/main/resources/static/js/travel-review.js
triptalkie/src/main/resources/templates/pages/travel-review/findTravelreviewAllList.html

**개요**
검색 기능 구현을 위해 city, country controller, service, mapper 생성.
**구현 내용**
- city, country controller, service, mapper 생성
**테스트 방법**
- Junit을 통해 테스트

feat: 검색 기능 구현을 위해 city, country controller, service, mapper 생성.

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/mapper/CommunityMapper.java

**개요**
git 충돌해결
**구현 내용**
git 충돌해결
**테스트 방법**
git 충돌해결

fix: communityMapper git 충돌 해결

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/service/CommunityService.java
triptalkie/src/main/resources/com/walkietalkie/triptalkie/mapper/CommunityMapper.xml

**개요**
git 충돌 mapper 해결
**구현 내용**
git 충돌 mapper 해결
**테스트 방법**
git 충돌 mapper 해결

fix: git 충돌 mapper 해결

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/CommnetTmpController.java
triptalkie/src/main/resources/static/js/comment.js
triptalkie/src/main/resources/static/js/mypage.js
triptalkie/src/main/resources/templates/pages/comment-tmp.html
triptalkie/src/main/resources/templates/pages/customerservice/faq.html
triptalkie/src/main/resources/templates/pages/customerservice/notice.html
triptalkie/src/main/resources/templates/pages/customerservice/qna.html

**개요**
댓글 기능 구현 중
**구현 내용**
댓글 기능 구현 중

feat:댓글 기능 구현 중

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/TravelReviewController.java
triptalkie/src/main/resources/templates/pages/travel-review/detail-review.html

**개요**
여행 후기 상세 페이지 로드 시 메이트 유형 없을 경우 화면에 뜨지 않도록 수정
**구현 내용**
- 여행 후기 상세 페이지 로드 시 메이트 유형 없을 경우 화면에 뜨지 않도록 수정
**테스트 방법**
- 프로그램 실행으로 확인 가능

fix : 여행 후기 상세 페이지 로드 시 메이트 유형 없을 경우 화면에 뜨지 않도록 수정

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/CommunityController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/CommunityService.java
triptalkie/src/main/resources/application.properties
triptalkie/src/main/resources/templates/pages/community/detail-community.html

**개요**
community 게시판 수정 , 삭제 버튼 고침
**구현 내용**
community 게시판 수정, 삭제 버튼 재수정
**테스트 방법**
sysout 을 찍어서 오류 지점을 정확히 체크

fix: comunity 수정, 삭제 버튼 고침

---

triptalkie/src/main/resources/static/css/make-mate.css

**개요**
사진 첨부 부분 백그라운드 컬러 수정
**구현 내용**
사진 첨부 부분 백그라운드 컬러 수정
**테스트 방법**

fix: 사진 첨부 부분 백그라운드 컬러 수정

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/MakemateChatController.java
triptalkie/src/main/resources/static/css/makemate-chat.css
triptalkie/src/main/resources/templates/layouts/base.html
triptalkie/src/main/resources/templates/pages/makemate-chat/chat.html

**개요**
메이트메이트 채팅 창 ui 구현
**구현 내용**
메이트메이트 채팅 창 ui 구현
**테스트 방법**
프로젝트 실행 시 확인 가능

feat: 메이트메이트 채팅 창 ui 구현

---

triptalkie/src/main/resources/com/walkietalkie/triptalkie/mapper/ChatMapper.xml

**개요**
채팅 기능 구현 중
**구현 내용**
채팅 기능 백엔드 구현 중
**테스트 방법**
-

Feat/ohs chatting - 채팅 기능 구현 중

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/HomeController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/domain/TravelReviewTop3DTO.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/mapper/TravelReviewMapper.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/TravelReviewService.java
triptalkie/src/main/resources/com/walkietalkie/triptalkie/mapper/TravelReviewMapper.xml
triptalkie/src/main/resources/static/css/content.css
triptalkie/src/main/resources/templates/home.html

**개요**
기존 코드를 수정하기 위해 dto 생성하여 나라 이름, 도시 이름과 함께 대표 이미지 사진 메인에 출력
**구현 내용**
- 홈 화면에 여행 후기 조회수 top 3 출력하였지만 해당 게시글의 이미지를 불러오지 못한 것을 DTO 생성하여 출력
- 이미지 아래 나라와 도시 표기
**테스트 방법**
- 프로젝트 실행하여 확인할 수 있음

feat : 기존 코드를 수정하기 위해 dto 생성하여 나라 이름, 도시 이름과 함께 대표 이미지 사진 메인에 출력

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/config/WebSocketConfig.java
triptalkie/src/main/resources/application.properties

**개요**
로그인 기능 개선
**구현 내용**
로그인 시 url에 JSESSIONID 자동으로 추가되는 현상 해결
**테스트 방법**
-

reafactor : 로그인 기능 개선

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/DTO/TravelReviewCommentDTO.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/TravelReviewCommentController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/TravelReviewController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/mapper/TravelReviewCommentMapper.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/TravelReviewCommentService.java
triptalkie/src/main/resources/com/walkietalkie/triptalkie/mapper/TravelReviewCommentMapper.xml
triptalkie/src/main/resources/static/js/travel-review.js
triptalkie/src/main/resources/templates/pages/travel-review/detail-review.html

**개요**
댓글 조회, 삭제 기능 구현
**구현 내용**
- 댓글 조회 기능 구현
- 댓글 삭제 기능 구현
**테스트 방법**
- 프로젝트 실행 혹은 JUnit 통하여 테스트

feat: 댓글 조회, 삭제 기능 구현

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/MakemateController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/domain/Memberlist.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/mapper/MakemateMapper.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/MakemateService.java
triptalkie/src/main/resources/com/walkietalkie/triptalkie/mapper/MakemateMapper.xml
triptalkie/src/main/resources/static/js/make-mate-knj.js
triptalkie/src/main/resources/templates/pages/make-mate/detail.html
triptalkie/src/main/resources/templates/pages/make-mate/list.html

**개요**
makemate 검색 기능 구현 완료
**구현 내용**
makemate 검색 기능 구현 완료
**테스트 방법**
logger, 브라우저 화면 확인

feat: makemate 검색 기능 구현 완료

---

triptalkie/src/main/resources/static/css/travel-review.css
triptalkie/src/main/resources/static/js/travel-review.js

**개요**
댓글 input, button 디자인 추가
**구현 내용**
댓글 input, button 디자인 추가
**테스트 방법**
프로젝트 실행하여 테스트 가능

style : 댓글 input, button 디자인 추가

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/domain/Member.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/MemberService.java
triptalkie/src/main/resources/com/walkietalkie/triptalkie/mapper/MemberMapper.xml

**개요**
회원 탈퇴시 로그인 안되게 로그인 기능 개선
**구현 내용**
회원 탈퇴 시 member 테이블 활성 상태 컬럼 0으로 변화
활성 상태 컬럼 체크해서 0이라면 로그인 안되게 로그인 기능 개선
**테스트 방법**
-

refactor : 회원 탈퇴시 로그인 안되게 로그인 기능 개선

---

triptalkie/src/main/resources/static/js/travel-review.js

**개요**
댓글 생성된 직후 수정 버튼 이벤트 추가하기 위해 코드 일부 수정
**구현 내용**
댓글 생성된 직후 수정 버튼 이벤트 추가하기 위해 코드 일부 수정
**테스트 방법**
프로젝트 실행 시 확인 가능

fix : 댓글 생성된 직후 수정 버튼 이벤트 추가하기 위해 코드 일부 수정

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/TravelInfoController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/domain/TravelInfoImage.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/mapper/TravelInfoImageMapper.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/TravelInfoImageService.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/TravelInfoService.java
triptalkie/src/main/resources/com/walkietalkie/triptalkie/mapper/TravelInfoImageMapper.xml
triptalkie/src/main/resources/com/walkietalkie/triptalkie/mapper/TravelInfoMapper.xml
triptalkie/src/main/resources/templates/pages/travel-info/detail.html
triptalkie/src/main/resources/templates/pages/travel-info/register.html

**개요**
여행 정보 글에 사진 등록, 사진 조회 기능 구현
**구현 내용**
여행 정보 글에 사진 등록, 사진 조회 기능 구현
**테스트 방법**
여행 정보 글에 사진 등록, 사진 조회 기능 구현

feat : 여행 정보 글에 사진 등록, 사진 조회 기능 구현

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/TravelInfoController.java
triptalkie/src/main/resources/templates/pages/travel-info/edit.html
triptalkie/src/main/resources/templates/pages/travel-info/register.html

**개요**
여행 정보 글 이미지 수정 기능 구현
**구현 내용**
여행 정보 글 이미지 수정 기능 구현
**테스트 방법**
-

feat : 여행 정보 글 이미지 수정 기능 구현

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/service/MemberService.java

**개요**
로그인 실패시 오류 페이지 발생 대신 메인페이지 이동하기 수정
**구현 내용**
로그인 실패시 오류 페이지 발생 대신 메인페이지 이동하기 수정
**테스트 방법**
-

fix : 로그인 실패시 오류 페이지 발생 대신 메인페이지 이동하기 수정

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/DTO/TravelInfoTop3DTO.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/HomeController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/mapper/TravelInfoMapper.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/TravelInfoService.java
triptalkie/src/main/resources/com/walkietalkie/triptalkie/mapper/TravelInfoMapper.xml
triptalkie/src/main/resources/templates/home.html

**개요**
여행 정보 조회수 별 top3 출력 시 기본 이미지를 설정하기 위해 코드 수정
**구현 내용**
여행 정보 조회수 별 top3 출력 시 기본 이미지를 설정하기 위해 코드 수정
dto 생성하여 썸네일 같이 조회
매퍼도 수정
**테스트 방법**
프로젝트 실행 혹은 JUnit

fix : 여행 정보 조회수 별 top3 출력 시 기본 이미지를 설정하기 위해 코드 수정

---

triptalkie/src/main/resources/templates/home.html

**개요**
메인에 여행정보 사진 뜨도록 경로 수정 완료
**구현 내용**
메인 - 여행정보 사진 안뜸 : 경로 수정 필요 /uploads/travelInfo
**테스트 방법**
프로젝트 실행하여 확인 가능

fix : 메인에 여행정보 사진 뜨도록 경로 수정 완료

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/TravelInfoController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/TravelInfoService.java
triptalkie/src/main/resources/com/walkietalkie/triptalkie/mapper/TravelInfoMapper.xml
triptalkie/src/main/resources/static/js/member.js
triptalkie/src/main/resources/templates/pages/travel-info/detail.html
triptalkie/src/main/resources/templates/pages/travel-info/edit.html

**개요**
**구현 내용**
로그인 -  alert 없애기
여행정보 - 상세페이지 화면 조회수 변화 없음 -> 조회수 반영되게 수정
여행정보 목록버튼 뒷페이지로만 간다. -> 목록으로 바로가게 수정
여행정보 삭제 안됨 : 405 error 컨트롤러에서 get인데 view에서 post으로 전송 -> view post -> controller post으로 수정
**테스트 방법**
웹 브라우저에서 테스트

fix : 버그 수정

---

triptalkie/src/main/resources/static/css/content.css
triptalkie/src/main/resources/static/css/customerservice.css
triptalkie/src/main/resources/templates/home.html
triptalkie/src/main/resources/templates/pages/customerservice/notice.html
triptalkie/src/main/resources/templates/pages/customerservice/qna.html

**개요**
- 메인 화면 notice 비율 조정
- notice 페이지 더미 수정 후 출력
- cs 각 title 추가
**구현 내용**
- 메인 화면 notice 비율 조정
- notice 페이지 더미 수정 후 출력
- cs 각 title 추가
**테스트 방법**
- 프로젝트 실행 후 확인 가능

fix: 메인 화면 notice 비율 조정, notice 페이지 더미 수정 후 출력, cs 각 title 추가

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/MypageController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/mapper/MypageMapper.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/MypageService.java

**개요**
mypage 불필요한 주석 제거 및 sysout 삭제
**구현 내용**
mypage 불필요한 주석 제거 및 sysout 삭제
**테스트 방법**

chore: mypage 불필요한 주석 제거 및 sysout 삭제

---

triptalkie/src/main/java/com/walkietalkie/triptalkie/controller/MypageController.java
triptalkie/src/main/java/com/walkietalkie/triptalkie/service/MypageService.java

**개요**
mypage 주석, sysout 삭제
**구현 내용**
mypage 주석, sysout 삭제
**테스트 방법**

chore: mypage 주석, sysout 삭제
